server:
  port: 8082

logging:
  level:
    root: error
    com.yc: info
    org.springframework: info

#在这个init中 只需要用到 spring创建datasource，用这个来init
#本地的配置 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yc125res?serverTimezone=UTC
    username: root
    password: 4444
    driver-class-name: com.mysql.cj.jdbc.Driver
